### ISSUE TITLE
Incomplete install instruction PyQT5

### ISSUE THREAD

**Issue by waterwin** [dspsandbox/Canvas#1]
PyQt5 (already included in the Anaconda 3 distribution):
pip install

**Comment by dspsandbox** [comment]
Indeed, I have just updated the  code snippet
Thanks!

**Comment by waterwin** [comment]
You ARE fast!
Kind regards,
ErwinPE3ES / F4VTQ
    On Monday, June 28, 2021, 02:27:25 PM GMT+2, Pau Gómez ***@***.***> wrote:  
 
 


Indeed, I have just updated the code snippet
Thanks!
